groupInfo:
  groupID: -1 #Сюда ваш ID группы (Опционально, можете не указывать)
  groupToken: 'yourTokenHere'
settings:
  delay: 15 #ВНИМАНИЕ! Не ставьте слишком низкие числа ( не ниже 10)
# Поддержка прокси серверов, необходим если сайт vk.com не работает
proxy:
  # NONE, HTTP, HTTPS, FTP, SOCKS
  type: NONE
  host: 'test.com'
  port: 1234